name: Test

on:
  push:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./
        id: changelog
        with:
          base: bcd6c5c83303667d07f8f0eefabffb6260b0e24f
      - name: Print changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"
  test-action-with-empty-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ./
        id: changelog
        with:
          base: ''
          head: ''
      - name: Print changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"
